[package]
name = "pirix"
version = "0.1.0"

[lib]
name = "kernel"
path = "kernel/kernel.rs"
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[dependencies.alloc_system]
path = "lib/alloc_system"
