Import("target")

env = target.Clone(
    LINKFLAGS="-T servers/link.ld",
    LIBS="pirix",
    LIBPATH=["#build/$ARCH/lib"],
)

env.Append(
    CFLAGS=["-Wall", "-fno-stack-protector"],
)


vfs = env.Program("vfs/vfs", env.Glob("vfs/*.c"))
devmgr = env.Program("devmgr/devmgr", env.Glob("devmgr/*.c"))