Import("target")

env = target.Clone(
    LIBPATH=["#build/$ARCH/lib"],
)

env.Append(
    CFLAGS=["-Wall", "-fno-stack-protector"],
)

servers = []
servers.append(env.Program("system/system", env.Glob("system/*.c")))
servers.append(env.Program("login/login", env.Glob("login/*.c")))

Return("servers")
