Import("target")

libs = []

libs.append(target.Library("pirix", Glob("pirix/*.c") + [
    "pirix/$ARCH/syscall.S"
]))

libs.append(target.Library("pthread", Glob("pthread/*.c")))

libs.append(target.Object("crt0", "pirix/${ARCH}/crt0.S"))

Return("libs")
